version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: tokyo-sento
      POSTGRES_PASSWORD: tokyo-sento
      POSTGRES_DB: tokyo-sento
    restart: always
    networks:
      - host
networks:
  host: